### ISSUE TITLE
DB Week 3 Feedback

### ISSUE THREAD

**Issue by orhantoy** [humayunadilshahzad/hyf-homework#4]
Hi @humayunadilshahzad :v:

Overall, nice work! 👍 Here's my feedback on things that are missing or could be improved.

- The `alter table` here changes the `price` column in a way you don't want to, can you figure out what is wrong?
  https://github.com/humayunadilshahzad/hyf-homework/blob/3b0774f9c68bc898b431df7bc1a0312cae58e4f2/databases/week3/mealsharing.sql#L15-L16
- Is it possible to name the column `when` instead of `when_date`:
  https://github.com/humayunadilshahzad/hyf-homework/blob/3b0774f9c68bc898b431df7bc1a0312cae58e4f2/databases/week3/mealsharing.sql#L10
- Does it have an effect to specify the size for `text` type?
  https://github.com/humayunadilshahzad/hyf-homework/blob/3b0774f9c68bc898b431df7bc1a0312cae58e4f2/databases/week3/mealsharing.sql#L8
- Minor typo:
  https://github.com/humayunadilshahzad/hyf-homework/blob/3b0774f9c68bc898b431df7bc1a0312cae58e4f2/databases/week3/mealsharing.sql#L29
- You seem to have all the correct solutions for the Meal, Reservation and Review queries 👍 
- In "Additional queries" you also have the correct solutions but you're missing the query for "Get meals that still has available reservations". Let me know if you need help with this one and what you have tried.

**Comment by orhantoy** [comment]
Hey! Have you had time to look into the feedback? Let me know if you have questions.

**Comment by humayunadilshahzad** [comment]
Hi Orhan .. thanx for you time and value able feed back ... yes I knew I am missing with one query .. but I completely forgot .. I will try and ask you for help if I am stuck 
thanx
